version: '3.3'

services:
  chatty-cathy:
    image: michaelkoconnor/chatty-cathy
    build: .
    depends_on:
      - redis
    #  command: ["./wait-for-it.sh", "db:5432", "--", "python", "app.py"]
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
    env_file: .env
    # restart: unless-stopped
    networks:
      - dev-network

  chatty-cathy1:
    image: michaelkoconnor/chatty-cathy
    build: .
    depends_on:
      - redis
    environment:
      NODE_ENV: production
    ports:
      - 4001:4000
    env_file: .env
    # restart: unless-stopped
    networks:
      - dev-network

  redis:
    image: redis
    container_name: cache
    restart: always
    ports:
      - 6379:6379
    networks:
      - dev-network

  # test:
  #   image: michaelkoconnor/chatty-cathy
  #   build: .
  #   environment:
  #     NODE_ENV: test
  #   command: npm test
  #   ports:
  #     - 4000:4000
  #   env_file: .env

networks:
  dev-network:
    driver: bridge
