version: '3.3'

services:
  chatty-cathy:
    image: michaelkoconnor/chatty-cathy
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
    env_file: .env
    restart: unless-stopped
