version: '3.3'

services:
  chatty-cathy:
    image: michaelkoconnor/chatty-cathy:1.0.0
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
    env_file: .env
    restart: unless-stopped

  test:
    image: michaelkoconnor/chatty-cathy
    build: .
    environment:
      NODE_ENV: test
    command: npm test
    ports:
      - 4000:4000
    env_file: .env
